name: onehub
description: A Github mobile client

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^1.0.0-beta.10
  another_flushbar: ^1.10.15
  cached_network_image: ^2.5.1
  connectivity: ^3.0.2
  dio_http_cache: ^0.2.11
  dio: ^3.0.10
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0-nullsafety.4
  flutter_countdown_timer: ^4.0.0
  flutter_emoji: ^2.2.1+1
  flutter_highlight:
    git:
      url: https://github.com/NamanShergill/onehub_highlight.dart.git
      ref: master
      path: flutter_highlight
  flutter_html:
    git:
      url: https://github.com/Sub6Resources/flutter_html.git
      ref: 4688f1a91421a76ea5c27e29889fadce6b6b4102
  flutter_icons: ^1.1.0
  flutter_secure_storage: ^4.1.0
  flutter_slidable: ^0.6.0-nullsafety.0
  flutter_signin_button: ^2.0.0-nullsafety.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  google_nav_bar:
    git:
      url: https://github.com/NamanShergill/onehub_google_nav_bar.git
      ref: master
  graphql: ^4.0.1
  infinite_scroll_pagination: ^3.0.1
  intl: ^0.17.0
  line_icons: ^2.0.1
  logger: ^1.0.0-nullsafety.0
  markdown: ^4.0.0
  mime: ^1.0.0
  page_transition: ^1.1.7+6
  path: ^1.8.0
  path_provider: ^2.0.1
  pretty_dio_logger: ^1.1.1
  provider: ^5.0.0
  share: ^2.0.1
  shimmer: ^2.0.0-nullsafety.0
  snapping_sheet: ^2.0.2
  url_launcher: ^6.0.2
  webview_flutter: ^2.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^1.0.0-beta.10
  build_runner: ^1.11.5

dependency_overrides:
  xml: ^5.0.2
  args: ^2.0.0
  quiver: ^3.0.0-nullsafety.3
  url_launcher: ^6.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
