name: gitapp
description: A Github mobile client

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  github: ^7.0.1
  provider: ^4.3.2
  auto_route: ^0.6.7
  dio: ^3.0.10
  flutter_cache_manager: ^1.4.1
  path_provider: ^1.6.11
  path: ^1.7.0
  flutter_secure_storage: ^3.3.3
  url_launcher: ^5.5.0
  flushbar: ^1.10.4
  flutter_markdown: ^0.4.3
  line_icons: ^0.2.0
  page_transition: ^1.1.6
  dotted_border: ^1.0.6
  flutter_spinkit: ^4.1.2+1
  custom_navigation_bar:
    path: modifiedPackages/custom_navigation_bar-0.2.7
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  build_runner: ^1.10.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
