name: dio_hub
description: A Github mobile client

publish_to: 'none'

version: 0.3.0-dev.internal

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.0
  auto_route: ^2.2.0
  another_flushbar: ^1.10.23
  cached_network_image: ^3.0.0
  connectivity: ^3.0.6
  device_info_plus: ^1.0.1
  dio: ^4.0.0
  dio_cache_interceptor: ^2.3.1
  equatable: ^2.0.2

  # Modified to remove the current typing word indicator.
  # Todo: Move back to main branch after breaking changes are fixed by maintainer.
  extended_text_field:
    git:
      url: https://github.com/NamanShergill/extended_text_field.git
      ref: temp

  flutter_bloc: ^7.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_datetime_picker: ^1.5.1
  flutter_emoji: ^2.2.1+1

  # Modified to add background color option.
  flutter_highlight:
    git:
      url: https://github.com/NamanShergill/highlight.dart.git
      ref: master
      path: flutter_highlight

  # Use until official release that fixes the lists.
  flutter_html:
    git:
      url: https://github.com/Sub6Resources/flutter_html.git
      ref: master

  flutter_icons: ^1.1.0
  flutter_inappwebview: ^5.3.2
  flutter_keyboard_visibility: ^5.0.2
  flutter_portal: ^0.4.0
  flutter_reaction_button: ^1.0.8
  flutter_scroll_to_top: ^1.1.0

  # Todo: Use this until official release that disables the logs.
  flutter_secure_storage:
    git:
      url: https://github.com/mogol/flutter_secure_storage.git
      ref: 2ad3cf2ea344b93742418af655537d2acc7043ec

  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
#  flutter_web_auth: ^0.3.0

  # Modified to support hero tags. Might remove.
  google_nav_bar:
    git:
      url: https://github.com/NamanShergill/google_nav_bar.git
      ref: master

  gql: ^0.13.0
  gql_exec: ^0.3.0

  # Added exception status codes for errors.
  gql_dio_link:
    git:
      url: https://github.com/NamanShergill/gql
      path: links/gql_dio_link


  gql_link: ^0.4.0
  infinite_scroll_pagination: ^3.0.1+1
  intl: ^0.17.0
  json_annotation: ^4.0.1
  line_icons: ^2.0.1
  logger: ^1.0.0
  markdown: ^4.0.0

  # Modified for additional markdown options.
  # Todo: Move to null safety.
  markdown_editable_textinput:
    git:
      url: https://github.com/NamanShergill/markdown-editable-textinput.git
      ref: master

  mime: ^1.0.0
  package_info_plus: ^1.0.1
  path_provider: ^2.0.2
  pretty_dio_logger: ^1.2.0-beta-1
  provider: ^5.0.0
  share: ^2.0.4
  shimmer: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  sliver_tools: ^0.2.4
  uni_links:
    git:
      url: https://github.com/objectivecosta/uni_links_simplified
  url_launcher: ^6.0.2

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  artemis: ^7.0.0-beta.11
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.4
  change_app_package_name: ^1.0.0
  dependency_validator: ^3.1.0
  flutter_native_splash: ^1.1.8+4
  flutter_lints: ^1.0.3
  json_serializable: ^4.1.3

#Temporary workaround until https://github.com/Milad-Akarie/auto_route_library/issues/569 is fixed.
dependency_overrides:
  analyzer: 1.5.0

flutter_native_splash:
  color: '#17181c'
  image: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
